name: Distribution Builds

on:
  # Automatically on every tag starting with v
  push:
    tags:
      - v*
  # Manual dispatch for testing
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up butler
        uses: jdno/setup-butler@v1
      - name: Test butler
        run: butler -V
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
      - name: Build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: --no-daemon html:dist
      - name: Deploy 🚀
        run: butler push html/build/dist sandramoen/kampenisse:html
